- name: Snake Evolution
  uses: miccy/snake-evolution@v1.3.0
  with:
    github_user_name: SaberPawsNEW
    github_token: # optional, default is 
    outputs: # optional, default is dist/snake.svg
    # Color theme (github-light, github-dark, ocean, sunset, neon-gamer, cypherpunk; glass planned with future GIF support)
    theme: # optional, default is github-dark
    # Year to generate contributions for
    year: # optional, default is 
